apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:catalogue-db-dev-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/mxw-sec/microservice-helmcharts
    targetRevision: main
    path: service-charts/catalogue-db
    helm:
      valueFiles:
        - /env/dev/catalogue-db/catalogue-db-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true