apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:frontend-staging-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/mxw-sec/microservice-helmcharts
    targetRevision: main
    path: service-charts/frontend
    helm:
      valueFiles:
        - "/env/staging/frontend/frontend-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true