apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:voting-prod-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/mxw-sec/microservice-helmcharts
    targetRevision: main
    path: service-charts/voting
    helm:
      valueFiles:
        - /env/prod/voting/voting-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
